# Generated by Django 3.0.5 on 2020-04-13 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Aplicacion.Actor')),
                ('Email', models.EmailField(max_length=254)),
            ],
            bases=('Aplicacion.actor',),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Aplicacion.Actor')),
            ],
            bases=('Aplicacion.actor',),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Momento', models.DateTimeField(auto_now_add=True)),
                ('Actor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Actor')),
                ('Partido', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acertado', models.BooleanField(default=False)),
                ('Partido', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Partido')),
                ('Usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Usuario')),
            ],
        ),
    ]
