# Generated by Django 3.0.5 on 2020-04-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensajeBienvenidaIn', models.CharField(max_length=60)),
                ('mensajeBienvenidaEs', models.CharField(max_length=60)),
                ('linkLogo', models.URLField()),
                ('valorComentariosPositivos', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaDeUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDeUsuario', models.CharField(max_length=32, unique=True)),
                ('contrasena', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLocal', models.CharField(max_length=35)),
                ('nombreVisitante', models.CharField(max_length=35)),
                ('resultado', models.CharField(max_length=35)),
                ('pronosticoSistema', models.CharField(max_length=35)),
                ('premio', models.PositiveIntegerField()),
                ('dificultad', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=35)),
                ('karma', models.IntegerField(default=0)),
                ('cuentaDeUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.CuentaDeUsuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=35)),
                ('acertado', models.BooleanField(default=False)),
                ('partido', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Partido')),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=35)),
                ('momento', models.DateTimeField(auto_now_add=True)),
                ('texto', models.CharField(max_length=35)),
                ('meGustas', models.PositiveIntegerField()),
                ('partido', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=35)),
                ('cuentaDeUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.CuentaDeUsuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
