# Generated by Django 3.0.5 on 2020-04-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaDeUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreDeUsuario', models.CharField(max_length=32, unique=True)),
                ('Contraseña', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=35)),
                ('Apellidos', models.CharField(max_length=35)),
                ('Email', models.EmailField(max_length=35)),
                ('Karma', models.IntegerField(default=0)),
                ('CuentaDeUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.CuentaDeUsuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
