# Generated by Django 3.0.5 on 2020-04-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=35)),
                ('Apellidos', models.CharField(max_length=35)),
                ('Email', models.EmailField(max_length=35)),
                ('Karma', models.IntegerField(default=0)),
            ],
        ),
    ]
