# Generated by Django 3.0.6 on 2020-05-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='actor',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='administrador',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
