# Generated by Django 3.0.6 on 2020-07-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='linkLogo',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='mensajeBienvenida',
        ),
    ]
