# Generated by Django 3.0.6 on 2020-05-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logro',
            name='usuario',
        ),
        migrations.AddField(
            model_name='logro',
            name='usuarios',
            field=models.ManyToManyField(null=True, to='aplicacion.Usuario'),
        ),
    ]
