# Generated by Django 3.0.5 on 2020-04-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20200424_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='meGustas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Partido'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='mensajeBienvenida',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='partido',
            name='dificultad',
            field=models.CharField(choices=[('Fácil', 'Facil'), ('Intermedia', 'Intermedia'), ('Difícil', 'Dificil')], max_length=35),
        ),
        migrations.AlterField(
            model_name='partido',
            name='pronosticoSistema',
            field=models.CharField(choices=[('1', 'Local'), ('X', 'Empate'), ('2', 'Visitante')], max_length=35),
        ),
        migrations.AlterField(
            model_name='partido',
            name='resultado',
            field=models.CharField(choices=[('1', 'Local'), ('X', 'Empate'), ('2', 'Visitante')], max_length=35),
        ),
    ]
