# Generated by Django 3.0.6 on 2020-05-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20200530_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logro',
            name='usuarios',
            field=models.ManyToManyField(to='aplicacion.Usuario'),
        ),
    ]
