# Generated by Django 3.0.6 on 2020-08-24 21:03

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20200822_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='pronosticoSistema',
            field=computed_property.fields.ComputedIntegerField(compute_from='calcular_pronostico', editable=False),
        ),
    ]
