# Generated by Django 3.0.5 on 2020-04-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20200429_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='pronosticoSistema',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='partido',
            name='resultado',
            field=models.CharField(max_length=35),
        ),
    ]
