# Generated by Django 3.0.6 on 2020-08-24 21:07

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_auto_20200824_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='pronosticoSistema',
            field=computed_property.fields.ComputedDecimalField(compute_from='calcular_pronostico', decimal_places=9, editable=False, max_digits=11),
        ),
    ]
