# Generated by Django 3.0.6 on 2020-05-13 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_auto_20200429_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentarioRespuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Comentario'),
        ),
    ]
