# Generated by Django 3.0.6 on 2020-05-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_comentario_comentariorespuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='dia',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='hora',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentarioRespuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Comentario'),
        ),
    ]
