# Generated by Django 3.0.6 on 2020-08-24 21:35

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_auto_20200824_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='goles_por_partido_del_equipo_local',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_por_partido_del_equipo_visitante',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partido',
            name='pronosticoSistema',
            field=computed_property.fields.ComputedIntegerField(compute_from='calcular_pronostico', editable=False),
        ),
        migrations.AlterField(
            model_name='partido',
            name='proporcion_de_puntos_del_equipo_local',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partido',
            name='proporcion_de_puntos_del_equipo_visitante',
            field=models.IntegerField(),
        ),
    ]
