# Generated by Django 3.0.6 on 2020-05-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_auto_20200513_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='dia',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='partido',
            name='hora',
            field=models.DateTimeField(),
        ),
    ]
