# Generated by Django 3.0.6 on 2020-08-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_auto_20200824_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='pronosticoSistema',
        ),
    ]
