# Generated by Django 3.0.6 on 2020-05-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_auto_20200513_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='dia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='partido',
            name='hora',
            field=models.TimeField(),
        ),
    ]
