# Generated by Django 3.0.6 on 2020-08-24 23:06

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_remove_partido_pronosticosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='pronosticoSistema',
            field=computed_property.fields.ComputedDecimalField(compute_from='calcular_pronostico', decimal_places=9, default=1, editable=False, max_digits=11),
            preserve_default=False,
        ),
    ]
