# Generated by Django 3.0.6 on 2020-08-24 23:24

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_partido_pronosticosistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='pronosticoSistema',
            field=computed_property.fields.ComputedDecimalField(compute_from='calcular_pronostico', decimal_places=2, editable=False, max_digits=11),
        ),
    ]
