# Generated by Django 3.0.6 on 2020-08-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_auto_20200825_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='goles_por_partido_del_equipo_local',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_por_partido_del_equipo_visitante',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='partido',
            name='proporcion_de_puntos_del_equipo_local',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='partido',
            name='proporcion_de_puntos_del_equipo_visitante',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
