# Generated by Django 3.0.6 on 2020-08-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_auto_20200825_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='goles_por_partido_del_equipo_local',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_por_partido_del_equipo_visitante',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partido',
            name='proporcion_de_puntos_del_equipo_local',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partido',
            name='proporcion_de_puntos_del_equipo_visitante',
            field=models.IntegerField(),
        ),
    ]
