# Generated by Django 3.0.6 on 2020-08-26 15:07

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0016_auto_20200826_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='probabilidadEmpate',
            field=computed_property.fields.ComputedDecimalField(compute_from='calcular_probabilidad_empate', decimal_places=9, default=94.48872829, editable=False, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partido',
            name='probabilidadVictoriaLocal',
            field=computed_property.fields.ComputedDecimalField(compute_from='calcular_probabilidad_victoria_local', decimal_places=9, default=2.42583774, editable=False, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partido',
            name='probabilidadVictoriaVisitante',
            field=computed_property.fields.ComputedDecimalField(compute_from='calcular_probabilidad_victoria_visitante', decimal_places=9, default=3.08543396, editable=False, max_digits=11),
            preserve_default=False,
        ),
    ]
